# 参考: https://blog.toshimaru.net/jekyll-deploy-with-github-actions/
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: bundle install
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Jekyll Build
        run: bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: blog.tekihei2317.com
